-- Add profile fields to app_users
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS bio VARCHAR(500);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS birthday VARCHAR(20);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS first_name VARCHAR(50);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS last_name VARCHAR(50);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS profile_color VARCHAR(20);
